### ISSUE TITLE
Light support

### ISSUE THREAD

**Issue by FlavorFx** [andrew-codechimp/ha-menu#26]
Great job! Please support lights as well. Templets are a good work around but not very hand.

**Comment by andrew-codechimp** [comment]
I have thought about lights but that leads to brightness and colour which would get a simple menu overly complex. My thoughts are leading to scene support but scenes don't have an off state so that adds its own issues.
I don't think switches will be the end and when I have some clear direction I'll add more functionality.
Leaving this issue open and welcome feedback.

**Comment by niccolobusato** [comment]
could be nice to have just on/off for light at the moment. i do not think is useful to change brightness or rgb on the actual dropdown menu.

**Comment by silvanverschuur** [comment]
I would appreciate it if you could add support for turning on/off lights.

**Comment by andrew-codechimp** [comment]
OK, I think I have a way forward with this that won't limit my plans later.
I'll try and get it added soon.

**Comment by FlavorFx** [comment]
Great!

**Comment by silvanverschuur** [comment]
Thanks!

**Comment by andrew-codechimp** [comment]
V1.10 now supports lights and input_booleans.
Groups in preferences now allows multiple groups, comma separated.  Ensure you add lights to your existing group or add the all_lights group.
