### ISSUE TITLE
Coma separated entities gives error in HA

### ISSUE THREAD

**Issue by crus1313** [andrew-codechimp/ha-menu#32]
You said:
"...can have multiple groups displayed in HA Menu by comma separating the entity id's."
https://hastebin.com/vinomuxosi.coffeescript
If I separate entities with a coma, HA gives sintax error.
https://hastebin.com/eyuyobulug.md
Please provide more info **with example** how this can be done.

Also just creating a group like your example does not do anything, restarting the app, and reloading HA groups still shows all entities (HA has a new group tho).

**Comment by andrew-codechimp** [comment]
Ok, first create your groups in ha as per the example.
Validate and restart HA. 
Then within the ha menu apps preference screen either replace the default all_switches,all_lights with the groups entityid (hamenu in my example) or add it to the list of groups with a comma. 
I was referring to the group entity ids rather than individual switches, lights. I’ll try and rewrite that to clarify. 


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andrew-codechimp** [comment]
Readme updated with step by step instructions.
